server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name:

word:
  model:
    import: classpath:docx/import.docx
    sub-model: classpath:docx/sub_model.docx

# 配置打印参数
optional:
  param: COLUMN_NAME,DATA_TYPE,PK,NULLABLE,DATA_DEFAULT,COMMENTS
  param_cn: 列名,数据类型,主键,可空,默认值,注释
