server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name: db-export

word:
  model:
    export: D:\\export.docx
    import: classpath:docx/import.docx
    sub-model: classpath:docx/sub_model.docx

# 配置打印参数
optional:
  param: COLUMN_NAME,DATA_TYPE,DATA_LENGTH,NULLABLE,DATA_DEFAULT,COMMENTS,PK
  param_cn: 列名,数据类型,长度,可空,默认值,注释,主键
