server:
  port: 9999
  servlet:
    context-path: /dbExport
spring:
  application:
    name: db-export

word:
  model:
    export: C:\Users\Administrator\Desktop\database-export-master\releaseJar\package\resources\export.docx
    import: C:\Users\Administrator\Desktop\database-export-master\releaseJar\package\resources\import.docx
    sub-model: C:\Users\Administrator\Desktop\database-export-master\releaseJar\package\resources\sub_model.docx